"""(Re)write the generated word-timing block inside every scene_{i}.tsx of a topic.

Scenes reference narration words through `at("mot", n)` instead of hard-coded frame numbers.
The block between the markers below is regenerated from the per-scene code prompts
(`cli_pipeline pre --step code`), so swapping the narration audio (e.g. the user's own voice)
re-syncs every animation without touching scene code.

Usage: python -m scripts.utility.retime_scenes --topic TOPIC [--init]
  --init  create scene stubs (block + helper only) for scenes that have no file yet
"""
import argparse
import glob
import json
import re
from pathlib import Path

OVG = Path(__file__).resolve().parents[2]
BEGIN = "/* @ovg-timings:begin -- generated by retime_scenes.py, do not edit by hand */"
END = "/* @ovg-timings:end */"

HELPER = r'''const MARKS = new RegExp("[" + String.fromCharCode(0x300) + "-" + String.fromCharCode(0x36f) + "]", "g");
const norm = (s: string): string => s.normalize("NFD").replace(MARKS, "").toLowerCase().replace(/[^a-z0-9]/g, "");
// Local frame at which the n-th occurrence of `word` starts being spoken in this scene.
// Apostrophes and hyphens split tokens (l ' actuariat), so pass the plain word: at("actuariat").
const at = (word: string, nth: number = 1): number => {
  const target = norm(word);
  let k = 0;
  for (const [w, f] of WORDS) {
    if (norm(w) === target) {
      k += 1;
      if (k === nth) return f;
    }
  }
  throw new Error("at(): word not found in this scene: " + word + " #" + nth);
};
'''


def parse_prompts(topic: str) -> dict:
    scenes = {}
    for p in glob.glob(str(OVG / "Outputs" / topic / "Video" / "Prompts" / "prompt_*.md")):
        if p.endswith("_original.md"):
            continue
        txt = Path(p).read_text(encoding="utf-8")
        for m in re.finditer(r"<scene_index>(\d+)</scene_index>\s*<scene_startFrame>(\d+)</scene_startFrame>\s*"
                             r"<scene_endFrame>(\d+)</scene_endFrame>.*?<audio_transcript_with_timings>(.*?)"
                             r"</audio_transcript_with_timings>", txt, re.S):
            idx, start, end, raw = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4).strip()
            parts = raw.split(", ")
            words = [(parts[i], int(parts[i + 1])) for i in range(0, len(parts) - 1, 2)]
            scenes[idx] = {"duration": end - start, "words": words}
    return scenes


def block(info: dict) -> str:
    words = ", ".join(json.dumps([w, f], ensure_ascii=True) for w, f in info["words"])
    return f"{BEGIN}\nconst DURATION = {info['duration']};\nconst WORDS: [string, number][] = [{words}];\n{END}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--topic", required=True)
    ap.add_argument("--init", action="store_true")
    a = ap.parse_args()
    scenes = parse_prompts(a.topic)
    latest = OVG / "Outputs" / a.topic / "Video" / "Latest"
    latest.mkdir(parents=True, exist_ok=True)
    for idx in sorted(scenes):
        f = latest / f"scene_{idx}.tsx"
        b = block(scenes[idx])
        if not f.exists():
            if a.init:
                f.write_text(f"// scene {idx}: timing block + helper, scene code to be written around them\n{b}\n{HELPER}", encoding="utf-8")
                print(f"scene {idx}: stub created ({scenes[idx]['duration']} frames)")
            continue
        src = f.read_text(encoding="utf-8")
        pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        if not pat.search(src):
            raise SystemExit(f"scene {idx}: timing markers missing in {f}")
        f.write_text(pat.sub(lambda _: b, src), encoding="utf-8")
        print(f"scene {idx}: retimed ({scenes[idx]['duration']} frames, {len(scenes[idx]['words'])} tokens)")


if __name__ == "__main__":
    main()
